name: 'Weblog.lol Importer'
description: 'WARNING: pre-pre-alpha status, you may lose data'
#inputs:
#  who-to-greet:  # id of input
#    description: 'Who to greet'
#    required: true
#    default: 'World'
#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
  - run: wget -O weblog-import.php https://api.omg.lol/address/adam/weblog/github-action
    shell: bash
  - run: php -f weblog-import.php $ADDRESS $WEBLOG_API_KEY
    shell: bash	
